#!/usr/bin/env python3
"""
Iteration Builder for Ralph-Lite
Part of Albatross Phase 4 - Core Build

Handles iterative building with checkpointing.
MVP: Creates placeholder files showing what WOULD be built.
Future: AI-generated actual code.
"""

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Optional
import shutil


@dataclass
class IterationResult:
    """Result of a single build iteration."""
    success: bool
    iteration_num: int
    files_created: List[str]
    files_modified: List[str]
    tests_passed: bool
    cost: float
    path: str
    summary: str


class IterationBuilder:
    """
    Handles iterative building with checkpointing.
    MVP: Creates placeholder files showing what WOULD be built.
    Future: AI-generated actual code.
    """

    def __init__(self, build_dir: str):
        self.build_dir = Path(build_dir).expanduser()
        self.current_iteration = 0

    def _slugify(self, text: str) -> str:
        """Convert text to directory-safe string."""
        return text.lower().replace(" ", "-")[:30]

    def create_scaffold(self, plan: str, plan_result: Dict) -> IterationResult:
        """
        Create initial project structure (Iteration 0).

        Args:
            plan: Implementation plan markdown
            plan_result: Plan approval result

        Returns:
            IterationResult with scaffold info
        """
        # Create iteration directory
        scaffold_dir = self.build_dir / "iteration-00-scaffold"
        scaffold_dir.mkdir(parents=True, exist_ok=True)

        # Create standard directories
        (scaffold_dir / "src").mkdir(exist_ok=True)
        (scaffold_dir / "tests").mkdir(exist_ok=True)

        # Create placeholder files
        files_created = []

        standard_files = [
            "src/main.py",
            "src/config.py",
            "tests/test_main.py",
            "README.md",
            "requirements.txt"
        ]

        for filename in standard_files:
            filepath = scaffold_dir / filename
            filepath.parent.mkdir(parents=True, exist_ok=True)

            # Write placeholder content
            content = f'''# {filename}
# Placeholder for {filename}
# TODO: Implement this file

"""
Generated by Ralph-Lite
Iteration: 0 (Scaffold)
Plan: See IMPLEMENTATION_PLAN.md
"""
'''
            filepath.write_text(content)
            files_created.append(filename)

        # Create PROGRESS.md
        progress_file = scaffold_dir / "PROGRESS.md"
        progress_file.write_text(f"""# Build Progress

## Project: {self.build_dir.name}

### Iteration 0: Scaffold
- Status: Complete
- Files created: {len(files_created)}
- Cost: $0.00

### Plan Summary
See IMPLEMENTATION_PLAN.md for full details.

### Next
Iteration 1: Core implementation
""")

        return IterationResult(
            success=True,
            iteration_num=0,
            files_created=files_created,
            files_modified=[],
            tests_passed=True,
            cost=0.0,
            path=str(scaffold_dir),
            summary=f"Created scaffold with {len(files_created)} files"
        )

    def build_iteration(self, iteration_num: int, task: str,
                       prev_iteration_path: str) -> IterationResult:
        """
        Execute one build iteration.

        Args:
            iteration_num: Current iteration number
            task: What to implement (e.g., "Add error handling")
            prev_iteration_path: Path to previous iteration

        Returns:
            IterationResult
        """
        # Create new iteration directory
        task_slug = self._slugify(task)
        iter_dir = self.build_dir / f"iteration-{iteration_num:02d}-{task_slug}"
        iter_dir.mkdir(parents=True, exist_ok=True)

        # Copy from previous iteration
        prev_dir = Path(prev_iteration_path)
        if prev_dir.exists():
            for item in prev_dir.iterdir():
                if item.is_file():
                    shutil.copy2(item, iter_dir / item.name)
                elif item.is_dir():
                    shutil.copytree(item, iter_dir / item.name, dirs_exist_ok=True)

        # "Implement" task (placeholder)
        files_modified = []
        main_file = iter_dir / "src" / "main.py"

        if main_file.exists():
            with open(main_file, "a") as f:
                f.write(f'''

# {"=" * 60}
# ITERATION {iteration_num}: {task}
# {"=" * 60}

# TODO: Implement {task}
# This is a placeholder showing what would be built.
#
# In full Ralph-Lite (Batch 2), this would be AI-generated code.
''')
            files_modified.append("src/main.py")

        # Update PROGRESS.md
        progress_file = iter_dir / "PROGRESS.md"
        existing = progress_file.read_text() if progress_file.exists() else ""
        progress_file.write_text(existing + f"""

### Iteration {iteration_num}: {task}
- Status: Complete (placeholder)
- Files modified: {len(files_modified)}
- Task: {task}

""")

        self.current_iteration = iteration_num

        return IterationResult(
            success=True,
            iteration_num=iteration_num,
            files_created=[],
            files_modified=files_modified,
            tests_passed=True,  # MVP: always True
            cost=0.10,  # MVP: fixed cost
            path=str(iter_dir),
            summary=f"Placeholder implementation for: {task}"
        )

    def run_tests(self, iteration_path: str) -> bool:
        """
        Run tests for an iteration.

        MVP: Always returns True
        Future: Actually run pytest
        """
        # Check if tests exist
        test_dir = Path(iteration_path) / "tests"
        if not test_dir.exists():
            return True  # No tests to run

        # MVP: Assume tests pass
        # Future: subprocess.run(["pytest", str(test_dir)])
        return True

    def create_final(self, last_iteration_path: str) -> Dict:
        """
        Create FINAL directory from last approved iteration.

        Args:
            last_iteration_path: Path to last good iteration

        Returns:
            Dict with path and file list
        """
        final_dir = self.build_dir / "FINAL"

        # Remove existing FINAL if present
        if final_dir.exists():
            shutil.rmtree(final_dir)

        # Copy last iteration to FINAL
        shutil.copytree(last_iteration_path, final_dir)

        # Add completion marker
        marker = final_dir / "BUILD_COMPLETE"
        marker.write_text(f"""Build completed: {datetime.now().isoformat()}
Status: READY FOR REVIEW
Deploy: Manual (copy to production when ready)
""")

        return {
            "path": str(final_dir),
            "files": [str(f.relative_to(final_dir))
                     for f in final_dir.rglob("*") if f.is_file()]
        }


# Convenience function
def create_builder(build_dir: str) -> IterationBuilder:
    """Factory function."""
    return IterationBuilder(build_dir)


if __name__ == "__main__":
    # Test
    import tempfile

    with tempfile.TemporaryDirectory() as tmpdir:
        builder = IterationBuilder(tmpdir)

        # Test scaffold
        result = builder.create_scaffold("test plan", {})
        print(f"Scaffold: {result.summary}")

        # Test iteration
        result2 = builder.build_iteration(1, "Add feature", result.path)
        print(f"Iteration 1: {result2.summary}")

        # Test final
        final = builder.create_final(result2.path)
        print(f"Final files: {len(final['files'])}")
